blank_issues_enabled: false
contact_links:
  - name: Preguntas generales
    url: https://github.com/jdiegocard/Clasificacion/discussions
    about: Abre una discusión si tu solicitud no es un bug/feature/story.
